@startuml
'https://plantuml.com/class-diagram

interface DeliveryChargeCalculator
class Beauty extends Product implements DeliveryChargeCalculator
class Grocery extends Product implements DeliveryChargeCalculator
class LargeAppliance extends Product implements DeliveryChargeCalculator


interface DeliveryChargeCalculator{
    BigDecimal getDeliveryCharge(weight, price)
    void show()
}

class Product{
    - name
    - price
    - weight
    # deliveryCharge

    + showProduct()
    + showDeliveryCharge(BigDecimal charge)
    + getWeight()
    + getPrice()
}

@enduml